config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  scope module: :public do
    root to:'homes#top'
    get 'about'=>"homes#about"
    get 'favorites'=> "favorites#index"
    patch 'users/withdraw/:id', to:'users#withdraw', as:"users/withdraw"
    resources :users,only:[:show,:edit,:update,:withdraw]
    resources :books,only:[:new,:index,:show,:edit,:update,:create,:destroy] do
      resource :favorites,only:[:create,:destroy]
      collection do
        get 'search'
      end
    end
  end

  namespace :admins do
    resources :books,only:[:index,:destroy]
    resources :users,only:[:index,:show,:edit,:update]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :book_image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  # has_many :evaluation_id, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true, length: { maximum: 200 }
  validates :star ,presence: true

  def get_book_image(width, height)
    unless book_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      book_image.attach(io: File.open(file_path), filename: 'default-image.jpg',content_type: 'image/jpeg,image/png')
    end
    book_image.variant(resize_to_fill:[width, height])
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :user_id, dependent: :destroy
  belongs_to :book_id, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:timeoutable,
         :recoverable, :rememberable, :validatable
  validates :family_name, presence: true,length: { maximum: 10 }
  validates :first_name, presence: true,length: { maximum: 10 }

  has_one_attached :user_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  has_many :evaluation_id, dependent: :destroy

  def get_user_image(width, height)
    unless user_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      user_image.attach(io: File.open(file_path), filename: 'default-image.jpg',content_type: 'image/jpeg')
    end
      user_image.variant(resize_to_fit:[width, height]).processed
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.family_name = "guestuser"
      user.first_name = "ゲスト"
    end
  end

end

app/controllers/admins/books_controller.rb
class Admins::BooksController < ApplicationController
  def index
    @books = Book.all.page(params[:page]).per(10)
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      redirect_to admins_books_path
    else
      render "index"
    end
  end

  private

  def book_params
    params.require(:book).permit(:name,:book_image,:introduction,:favorite_id,:user_id,:star)
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admins_users_path
  end

  private

  def user_params
    params.require(:user).permit(:family_name,:first_name,:family_name_kana,:first_name_kana,:email,:is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
   if current_admin
      admins_users_path
   elsif current_user
        books_path
   end
  end

  def after_sign_out_path_for(resource)
        root_path
  end

 protected

 def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up,keys: [:family_name, :first_name, :family_name_kana, :first_name_kana, :email, :is_deleted])
  devise_parameter_sanitizer.permit(:account_update,keys: [:family_name, :first_name, :family_name_kana, :first_name_kana, :email, :is_deleted])
 end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :ensure_normal_user, only: :destroy

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to books_path, notice: 'guestuserでログインしました。'
  end

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end
end

app/helpers/admins/books_helper.rb
module Admins::BooksHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/books/destroy.html.erb
<h1>Admins::Books#destroy</h1>
<p>Find me in app/views/admins/books/destroy.html.erb</p>

app/views/admins/books/index.html.erb
<div class="container pt-5 px-sm-0">
  <div class="row">
    <div class="md-3">
      <h3>書籍一覧</h3>
    </div>
  </div>
  <div class="row">
    <table class="table table-hover table-bordered mt-5">
        <thead>
          <tr>
            <th>書籍ID</th>
            <th>画像</th>
            <th>タイトル</th>
            <th>紹介</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= book.id %></td>
              <td>
                <%= image_tag book.get_book_image(100,100) %>
              </td>
              <td>
                <%= book.name %>
              </td>
              <td>
                <%= book.introduction %>
              </td>
              <td>
                <%= link_to admins_book_path(book.id),method: :delete do %>
                  <p class="btn btn-danger">削除する</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
    </table>
  </div>
  <div class="row">
    <%= paginate @books %>
  </div>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/admins/users/edit.html.erb
<div class="container pt-5 px-sm-0 text-center">
  <div class="row">
    <div class="col-8 text-center">
      <h3><%= @user.family_name %>  <%= @user.first_name %>さんの会員情報編集</h3>
    </div>
  </div>
  <%= form_with model: @user,url: admins_user_path do |f| %>
    <div class="row mt-5">
      <div class="col-md-3">
        <%= f.label :会員ID %>
      </div>
      <div class ="col-md-5 text-left">
        <%= @user.id %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-md-3">
        <%= f.label :氏名 %>
      </div>
      <div class ="col-md-3">
        <%= f.text_field :family_name, autofocus: true, autocomplete: "name", class:"form-control",placeholder: '氏' %>
      </div>
      <div class="col-md-3">
        <%= f.text_field :first_name, autocomplete: "name",  class:"form-control",placeholder: '名' %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-md-3">
        <%= f.label :フリガナ %>
      </div>
      <div class ="col-md-3">
        <%= f.text_field :family_name_kana, autocomplete: "name", class:"form-control" %>
      </div>
      <div class="col-md-3">
        <%= f.text_field :first_name_kana, autocomplete: "name",  class:"form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-md-3">
        <%= f.label :メールアドレス %>
      </div>
      <div class ="col-md-5">
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-md-3">
        <%= f.label :会員ステータス %>
      </div>
      <div class ="col-md-3">
        <%= f.radio_button :is_deleted, false %> 有効
        <%= f.radio_button :is_deleted, true %> 退会
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-md-6">
        <%= f.submit "変更を保存", class:"btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admins/users/index.html.erb
<!--管理者一覧大枠-->
<div class="container pt-5 px-sm-0">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <h3>会員一覧</h3>
    </div>
  </div>
  <div class="row">
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td>
              <%= link_to admins_user_path(user.id) do %>
                <%= user.family_name %><%= user.first_name %>
              <% end %>
            </td>
            <td><%= user.email %></td>
            <td>
              <% if user.is_deleted == true %>
                <span class="label label-secondary">退会</span>
              <% else %>
                <span class="label label-success">有効</span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="">
    </div>
  </div>
</div>

app/views/admins/users/show.html.erb
<!--管理者会員詳細大枠-->
<div class="container pt-5 px-sm-0 text-center">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <h3><%= @user.family_name %>  <%= @user.first_name %>さんの会員詳細</h3>
    </div>
  </div>
  <div class="row">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td><label>会員ID</label></td>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <td><label>氏名</label></td>
            <td><%= @user.family_name %>　<%= @user.first_name %></td>
          </tr>
          <tr>
            <td><label>フリガナ</label></td>
            <td><%= @user.family_name_kana %>　<%= @user.first_name_kana %></td>
          </tr>
          <tr>
            <td><label>メールアドレス</label></td>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <td><label>会員ステータス</label></td>
            <td>
              <% if @user.is_deleted == true %>
               <span class="label label-secondary">退会</span>
              <% else %>
               <span class="label label-success">有効</span>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
        <div class="col-6 text-center">
          <%= link_to "編集する", edit_admins_user_path(@user), class: "btn btn-success" %>
        </div>
        <div class="col-6 text-left">
          <%= link_to "戻る", admins_users_path, class: "btn btn-primary ml-5" %>
        </div>
    </div>
  </div>

app/views/layouts/_header.html.erb
<header class="header shadow-sm w-100">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <% if user_signed_in? %>
        <button type="button" class="btn-side p-3"><i class="fas fa-angle-double-down"></i></button>
      <% end %>
      <a class="nav navbar-brand p-3 text-info" href="/"><%= image_tag 'Logo.png', size: "180x250", class: "mx-auto d-block img-fluid" %></a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-info' %>
            </li>
            <li class="nav-item">
              <%= link_to "説明", about_path, class: 'nav-link text-info' %>
            </li>
            <li class="nav-item">
              <%= link_to '書籍一覧', books_path, class: 'nav-link text-info' %>
            </li>
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-info' %>
            </li>
            <li class="nav-item">
              <%= link_to "会員一覧", admins_users_path, class: 'nav-link text-info' %>
            </li>
            <li class="nav-item">
              <%= link_to '書籍一覧', admins_books_path, class: 'nav-link text-info' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-info' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-info' %>
            </li>
            <li class="nav-item">
              <%= link_to "説明", about_path, class: 'nav-link text-info' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div class="collapseSide">
  <nav class="sidebar">
    <div class="brand p-4 flex-column m-o">
      <h3 class="listings_header">side menu</h3>
    </div>
    <ul class ="nav flex-column m-o p-3 mt-3">
      <li class = 'nav-item mb-2 ml-2 list-unstyled'><%= link_to 'マイページ', user_path(current_user.id), class: "nav-link w-100 h-100" %></li>
      <li class = 'nav-item mb-2 ml-2 list-unstyled'><%= link_to 'お気に入り', favorites_path, class: "nav-link w-100 h-100" %></li>
      <li class = 'nav-item mb-2 ml-2 list-unstyled'><%= link_to '書籍登録', new_book_path, class: "nav-link w-100 h-100" %></li>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningBooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="main <%= controller.controller_name %>">
    <% if current_page?(root_path) %>
      <div id="splash">
        <div id="splash_logo"><%= image_tag 'top-logo.png', class: "fadeUp mx-auto d-block img-fluid" %></div>
      </div>
    <% end %>
    <%= render 'layouts/header' %>
    <div class="index <%= controller.action_name %>">
      <% if user_signed_in? %>
        <%= render 'layouts/sidebar' %>
      <% end %>
      <div class="main-index">
        <%= yield %>
        <% if user_signed_in? %>
          <span id="back">
            <a href="">
              <%= image_tag asset_path('arrow.png'), data: {"turbolinks"=>false}, class: "arrow" %>
            </a>
          </span>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>